Add a reset button to views
localgovdrupal/localgov_events pull request #154
Opened 2024-08-27 12:17 UTC by zackdavies

Reset button added to both Events views. For https://github.com/localgovdrupal/localgov_events/issues/153

2024-09-03 09:40 UTC, ekes commented on localgov_events.install
> +function localgov_events_update_10001($is_syncing) {
Update hooks don't have a $is_syncing, they aren't called in syncing. They do have a sandbox argument - used for batching if I recall - but it's not required.

I again however feel queezy here pushing a button into live sites. How high are the chances of causing unexpected layout / presentation breakages for custom themes that have been built without it?

2024-09-03 10:12 UTC, ekes requested changes, later dismissed
For sure this will want the update hook correcting, but possibly removing.

2024-09-12 10:37 UTC, zackdavies commented
OK, update job removed as requested.

2024-10-21 22:15 UTC, andybroomfield approved these changes
Happy to approve this.

2024-11-05 12:08 UTC, merged