Update date_recur and date_recur_modular to ^3.0 for Drupal 9.
localgovdrupal/localgov_events pull request #25
Opened 2021-03-17 22:25 UTC by finnlewis

2021-05-08 09:16 UTC, ekes requested changes

2021-05-08 09:16 UTC, ekes commented on composer.json
> +        "drupal/date_recur_modular": "^2.0||^3.0",
I don't think we can do this safely.

We can't guarantee that < 4.0 isn't going to diverge from 2.0 such that it breaks. Actually the opposite, I think we can and should expect it to. Looking at development we might be safe to fix it at ~3.0.0 for date_recur as there is already work on 3.1, but even that isn't guaranteed. For date_recur_modular that's not the case. The developer has signaled a major version change and they aren't guaranteeing 3.0.* will be compatible with 2.0.*

2021-05-08 11:42 UTC, andybroomfield commented on composer.json
> +        "drupal/date_recur_modular": "^2.0||^3.0",
From https://www.drupal.org/project/date_recur

## Versions

Major version | 1 | 2 | ~3.0 | ^3.1 (Future)
-- | -- | -- | -- | --
Drupal core|8 only | 8 only | 9 only
API (Recurring Date Field internal API)|2017 | 2019
RR Library|^1 | ^1 | ^1 | ^1
PHP Compatibility|^5 | >=7.1 | >=7.3 | >=7.4
Stability|Stable | Stable | Stable | N/A
Support|Security only | Security and Bugs fixes | New features | New features
&nbsp;|Until June 2021 | Until Drupal 8 EOL | Until June 2023 | Until Drupal 9 EOL

I suggest locking this at 3.0.
Then when date recur 3.1 is released, this module should be bumped to 2.0 and explicitly require `^3.1`

Alternatively joint release a 2.0 version of localgov_events that is Drupal 9 only.

2021-05-10 14:46 UTC, ekes commented on composer.json
> +        "drupal/date_recur_modular": "^2.0||^3.0",
> Alternatively joint release a 2.0 version of localgov_events that is Drupal 9 only.

Think this is where we're going now.

2021-05-18 15:32 UTC, stephen-cox approved these changes

2021-05-18 15:35 UTC, merged